version: "3.4"
services:
    ampher-server:
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/amd64
        volumes:
            - .:/app
        ports:
            - 5001:5001
